# Generated by Django 3.1.2 on 2020-11-01 06:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
