# Generated by Django 3.1.2 on 2020-11-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_business_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_email',
            new_name='email',
        ),
    ]
