# Generated by Django 3.1.2 on 2020-11-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20201101_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user',
            new_name='business_owner',
        ),
    ]
