# Generated by Django 3.1.2 on 2020-11-02 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0004_auto_20201101_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neigborhood_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.neighborhood')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.neighborhood'),
        ),
    ]
