# Generated by Django 3.1.2 on 2020-11-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_auto_20201102_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate.neighborhood'),
        ),
    ]
