# Generated by Django 3.1.2 on 2020-11-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_auto_20201102_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='title',
        ),
    ]
