# Generated by Django 3.1.2 on 2020-11-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_auto_20201103_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='title',
            new_name='name',
        ),
    ]
