# Generated by Django 3.1.2 on 2020-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_auto_20201103_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
