# Generated by Django 3.1.2 on 2020-11-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_auto_20201103_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='occupant_count',
            field=models.IntegerField(null=True),
        ),
    ]
